server:
  port: 8011
  servlet:
    context-path: /buyermgt
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: buyermgt
logging:
  level:
    com.gokulr488.spring.buyermgt: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level- %msg%n'