server:
  port: 8010
  servlet:
    context-path: /payments
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: PAYMENTS
logging:
  level:
    com.gokulr488.spring.payments: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level- %msg%n'